feat: 댓글,게시판 Dto 기능 추가
alsqja/BugFixHub pull request #16
Opened 2024-11-21 12:02 UTC by beunyeong

2024-11-21 12:05 UTC, alsqja requested changes
201 CREATED
{
    “id”: 1,
    “userId”: 1,
    “commentId”: 1
}

201 CREATED
{
    “id”: 1,
    “userId”: 1,
    “postId”: 1
}

api 상으로 이런 형식 아니였나요?

2024-11-21 12:44 UTC, chohyuun approved these changes

2024-11-21 12:51 UTC, gimdonggeon commented on src/main/java/com/example/bugfixhub/dto/likes/CommentLikeResDto.java
commentId의 변수타입을 Long으로 잡아야 할 것 같습니다. 
아래 postId도 변수타입 수정이 필요할 것 같습니다.

2024-11-22 00:05 UTC, alsqja approved these changes

2024-11-22 00:05 UTC, merged