feat 댓글 CUD 기능 생성
alsqja/BugFixHub pull request #8
Opened 2024-11-20 13:04 UTC by gimdonggeon

댓글 CUD 기능 추가

2024-11-20 13:15 UTC, chohyuun requested changes

2024-11-20 13:15 UTC, chohyuun commented on src/main/java/com/example/bugfixhub/service/comment/CommentServiceImpl.java
댓글 생성 코드에서 400error 내용이나 게시글 아이디가 안들어 왔을때의 예외처리가 빠진것 같습니다!.
확인 부탁드립니다~

2024-11-21 00:16 UTC, alsqja requested changes
- 수정, 삭제 요청 시 save 한번 더 호출할 필요 없을거 같습니다.(service)
- 수정, 삭제는 본인과 post 의 작성자도 가능합니다.

2024-11-21 01:17 UTC, beunyeong approved these changes

2024-11-21 01:18 UTC, chohyuun approved these changes

2024-11-21 01:23 UTC, alsqja approved these changes

2024-11-21 01:23 UTC, merged